# Generated by Django 4.0.5 on 2022-06-24 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maincatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/maincatagory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/product')),
                ('og_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('mcate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.maincatagory')),
            ],
        ),
    ]
